apiVersion: v1
kind: Template
metadata:
  name: hawtio-online
parameters:
- name: ROUTE_HOSTNAME
  description: The externally-reachable host name that routes to the Hawtio Online service
  required: true
- name: OPENSHIFT_WEB_CONSOLE_URL
  description: The externally-reachable URL that routes to the OpenShift Web console
  required: false
message: |-
  Hawtio Online is deployed to ${ROUTE_HOSTNAME}.
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: hawtio-online
  data:
    hawtconfig.json: |
      {
        "about": {
          "title": "Hawtio OpenShift Console",
          "productInfo": [],
          "additionalInfo": "The Hawtio OpenShift Console eases the discovery and management of 'hawtio-enabled' applications deployed on OpenShift.",
          "copyright": ""
        },
        "branding": {
          "appName": "Hawtio OpenShift Console",
          "appLogoUrl": "img/hawtio-logo.svg"
        },
        "disabledRoutes": []
      }
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: hawtio-integration
  data:
    hawtconfig.json: |
      {
        "branding": {
          "appName": "Hawtio Integration Console",
          "appLogoUrl": "img/hawtio-logo.svg",
          "aboutDescription": "The Hawtio Integration Console enables introspecting Java applications."
        },
        "disabledRoutes": []
      }
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: hawtio-online
    labels:
      app: hawtio
      component: online
  spec:
    tags:
    - from:
        kind: DockerImage
        name: docker.io/hawtio/online:latest
      importPolicy:
        scheduled: true
      name: latest
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: hawtio
      component: online
    name: hawtio-online
  spec:
    replicas: 1
    selector:
      app: hawtio
      component: online
      deploymentconfig: hawtio-online
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: hawtio
          component: online
          deploymentconfig: hawtio-online
      spec:
        containers:
        - image: hawtio/online
          imagePullPolicy: Always
          name: hawtio-online
          ports:
          - name: nginx
            containerPort: 8443
          livenessProbe:
            httpGet:
              path: /online
              port: nginx
              scheme: HTTPS
            periodSeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /online
              port: nginx
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
          env:
          - name: HAWTIO_ONLINE_MODE
            value: cluster
          - name: HAWTIO_ONLINE_GATEWAY
            value: 'true'
          - name: OPENSHIFT_WEB_CONSOLE_URL
            value: ${OPENSHIFT_WEB_CONSOLE_URL}
          - name: OPENSHIFT_CLUSTER_VERSION
            value: '4'
          resources:
            requests:
              cpu: 0.2
              memory: 32Mi
            limits:
              cpu: 1.0
              memory: 32Mi
          volumeMounts:
          - name: hawtio-online
            mountPath: /usr/share/nginx/html/online/hawtconfig.json
            subPath: hawtconfig.json
          - name: hawtio-integration
            mountPath: /usr/share/nginx/html/integration/hawtconfig.json
            subPath: hawtconfig.json
          - mountPath: /etc/tls/private/serving
            name: hawtio-online-tls-serving
          - mountPath: /etc/tls/private/proxying
            name: hawtio-online-tls-proxying
        volumes:
        - name: hawtio-online
          configMap:
            name: hawtio-online
        - name: hawtio-integration
          configMap:
            name: hawtio-integration
        - name: hawtio-online-tls-serving
          secret:
            secretName: hawtio-online-tls-serving
        - name: hawtio-online-tls-proxying
          secret:
            secretName: hawtio-online-tls-proxying
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - hawtio-online
        from:
          kind: ImageStreamTag
          name: hawtio-online:latest
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: hawtio
      component: online
    annotations:
      service.beta.openshift.io/serving-cert-secret-name: hawtio-online-tls-serving
    name: hawtio-online
  spec:
    ports:
    - port: 443
      protocol: TCP
      targetPort: nginx
    selector:
      app: hawtio
      component: online
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: hawtio
      component: online
    name: hawtio-online
  spec:
    host: ${ROUTE_HOSTNAME}
    to:
      kind: Service
      name: hawtio-online
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: reencrypt
- apiVersion: v1
  kind: OAuthClient
  metadata:
    name: hawtio-online
  redirectURIs:
  - https://${ROUTE_HOSTNAME}