apiVersion: v2
name: hawtio-online
description: A Helm chart for installing HawtIO
type: application
version: 1.0.4
appVersion: 2.4.0
keywords:
  - hawtio
  - camel
  - console
  - jmx
  - react
home: https://hawt.io
sources:
  - https://github.com/hawtio/hawtio-online.git
